apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 2
  selector:
    matchLabels:
      name: back
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
      - name: back
        image: kontinu/go-expert:v1.0
        ports:
        - name: back
          containerPort: 8080
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  selector:
    name: back
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 8080